#ifndef COSMOS_PLUS_MEMORY_MAP_H
#define COSMOS_PLUS_MEMORY_MAP_H

#define DRAM_START_ADDR				0x00100000

#define MEMORY_SEGMENTS_START_ADDR		DRAM_START_ADDR

#define FTL_MANAGEMENT_START_ADDR		0x30000000			// FW DRAM START ADDRESS
#define DMA_MEMORY_START_ADDR		FTL_MANAGEMENT_START_ADDR	// For Data buffer

#define DRAM_END_ADDR				0x3fffffff

#define DMA_MEMORY_BUFFER_SIZE			0xf000000
#define DMA_MEMORY_ADMIN_SIZE			0x1000000 // for admin identify


#define NAND_START_ADDR 	0x43c00000


#define NVME_START_ADDR 	0x83c00000

#endif /* COSMOS_PLUS_MEMORY_MAP_H */
